name: CI-CD Spring Boot with SonarQube and Docker Hub

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  vulnerabilities-scan:
    name: Scan for Vulnerabilities
    runs-on: ubuntu-latest
  
    steps:
     - name: Checkout code
       uses: actions/checkout@v3
    
     - name: Set up JDK 17
       uses: actions/setup-java@v3
       with:
         java-version: '17'
         distribution: 'zulu'
    
     - name: Build project (without tests)
       run: mvn clean install -DskipTests
    
     - name: Install Trivy
       run: |
         curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
    
     - name: Scan for vulnerabilities in dependencies (Maven)
       run: |
         trivy fs \
           --scanners vuln \
           --vuln-type library \
           --severity CRITICAL,HIGH \
           --exit-code 1 \
           --ignore-unfixed \
           --format table \
           .
           
  build-and-sonar:
    name: Build & SonarQube Analysis (Quality)
    needs: vulnerabilities-scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Necessário para análise completa no SonarQube

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # Build + Testes
      - name: Build com Maven (testes inclusos)
        run: mvn -B clean verify

      # Sonar Scanner para projetos Maven
      - name: Análise no SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}

  docker-publish:
    name: Build & Push Docker Image
    needs: build-and-sonar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Projeto
        run: mvn clean install -DskipTests

      - name: Build e Push da imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/vekclient:latest
            ${{ secrets.DOCKERHUB_USER }}/vekclient:${{ github.sha }}
